Add a default value for default_port
When the server uses the default port of 19132, we should be able to omit the port number instead of
```
>>> bs.lookup("example.org")
ValueError: Given address 'example.org' doesn't contain port and default_port wasn't specified, can't parse.
```